### ISSUE TITLE
[EXPLORE] Create Hub Explore Route and View (Connected)

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo-deprecated#252]
## Overview

Create the connected view for the Explore route. This is accessed via the _Explore_ tab in the navigation.

![Image](https://user-images.githubusercontent.com/9438776/175975846-a61018ec-3e58-4250-b3dd-cdf54fe0c689.png)

## User Stories

- As a connected user, I should be able to see a list of all of the DAOs I'm in with relevant information.

## Details

- This is the main view for the Explore
- Populates the DAO Table information based on the user's DAOs

**Comment by jordanlesich** [comment]
We'll need to figure out what this actually is.

**Comment by jonathanprozzi** [comment]
We'll revisit this one after we handle Filtering/Searching/Sorting and we'll likely need to work with Pagination for this

**Comment by earth2travis** [comment]
Added to: https://github.com/HausDAO/daohaus-monorepo-deprecated/issues/985
