### ISSUE TITLE
Revise ValidNetwork, Keychain, NetworkObject Data Models

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/daohaus-monorepo-deprecated#267]
Typescript has an issue with how nested conditional objects are structured. This is causing challenges, particularly with the Keychain and KeychainList data types. 

There are utilities that combine these Keychains into a mass network object already written. I'm thinking we can potentially use these as a 'best of both worlds' solution. 

https://github.com/HausDAO/daohaus-monorepo/blob/b2a116790856a3055b4a5e27d200847ed4220c65/libs/common-utilities/src/constants/chainData.ts#L73 

It's worthwhile to investigate and see if we can use these utils to compose Keychains into a global network object. Hopefully this works with TS. If it doesn't, then we may need to think of something else. Preferably something that doesn't involve dumping all of the keys and endpoints into one object as that become a bit messy in V2. 

Also worth looking to see if there's a TS solution for dealing with existing data models.

**Comment by earth2travis** [comment]
This should be in now. @jordanlesich is this still an issue?

**Comment by jordanlesich** [comment]
Thinking I could fold this reorg into Brian's reorg once he's close to finish. Thinking that any larger pattern changes could move over there.

**Comment by earth2travis** [comment]
@brossetti1 are you still working on a reorg related to this issue?
