### ISSUE TITLE
Adjust the placeholder voting and non-voting stake values in the Starting Members input

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo-deprecated#369]
## Overview

Instead of having the placeholder value be `0x000... 30 10` we can populate it with values that are likely to be more commonly used, such as `0x000 10 0` (10 voting stake, 0 non-voting stake)

![image](https://user-images.githubusercontent.com/9438776/177386604-78dc5f6f-260d-435a-83c6-80472df32444.png)

**Comment by earth2travis** [comment]
Updated placeholder

https://github.com/HausDAO/monorepo/pull/81
