### ISSUE TITLE
Update Getting Started Page

### ISSUE THREAD

**Issue by TravisWyche** [HausDAO/daohaus-monorepo-deprecated#465]
Write a compelling introduction to the v3 docs. Possibly use GPT-3 to supplement?

**Comment by earth2travis** [comment]
There are some notes with comments from the HackMD file to incorporate into this page: https://hackmd.io/SRCeeWL7Ty27_gR29QSbYg?both#Getting-Started-Comments

**Comment by jonathanprozzi** [comment]
Made some improvements to this but will do another refinement pass and then I think we can close this out @earth2travis

**Comment by jonathanprozzi** [comment]
https://github.com/HausDAO/sdk-docs/pull/50 @earth2travis

**Comment by jonathanprozzi** [comment]
https://github.com/HausDAO/sdk-docs/pull/52

**Comment by jonathanprozzi** [comment]
Closed by https://github.com/HausDAO/sdk-docs/pull/52

Will continue to add more to this, but the content is in
