### ISSUE TITLE
Write 'Form Builder' section

### ISSUE THREAD

**Issue by TravisWyche** [HausDAO/daohaus-monorepo-deprecated#473]
https://hackmd.io/@daohaus/V3Docs-FormBuilder

**Comment by jonathanprozzi** [comment]
@earth2travis Working on this -- have a recording and notes from the demo on Friday but there's quite a lot to sift through still.

**Comment by jonathanprozzi** [comment]
https://github.com/HausDAO/sdk-docs/pull/52

**Comment by jonathanprozzi** [comment]
Closed by https://github.com/HausDAO/sdk-docs/pull/52

Will continue to add more to this, but the content is in
