### ISSUE TITLE
Create DAOhaus App Starter Templates

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo-deprecated#500]
## Overview

Create starter app templates that leverage our packages. We can start by creating these as repos that folks can clone, but then we can consider moving into a CLI similar to `create-next-app` once we iron things out.

These starts are a way for us to test out our packages outside of the monorepo and will also allow us to further test out how our packages are working for external developers (the _Buidler Persona_). 

This should be well documented and considered as part of our product offering as this can directly help with onboarding community devs.

## Details

- Create a repo that supports starter templates for use with Vite React and Next.js
- Should include our packages (component library, commons, and SDK)
- Test out how this works and any painpoints that we can resolve along the way
- Look toward what we'd want to establish to create a CLI tool that allows for various options similar to `create-next-app`

**Comment by jonathanprozzi** [comment]
@earth2travis @skuhlmann -- not sure what labels make sense for this type of project -- we can move add some that make sense as we work on things similar to this

**Comment by earth2travis** [comment]
This is a high priority this week. @alexkeating will jump in to help @jonathanprozzi. @brossetti1 will support

**Comment by earth2travis** [comment]
We have a design template here if we want to add this: https://github.com/HausDAO/daohaus-monorepo-deprecated/issues/1044
