### ISSUE TITLE
Clean Up NPM Organization

### ISSUE THREAD

**Issue by brossetti1** [HausDAO/daohaus-monorepo-deprecated#583]
# issue

we have some packages that are no longer active 

- [@daohaus/haus-sdk](https://www.npmjs.com/package/@daohaus/haus-sdk)

and soon:

- [@daohaus/local-abis](https://www.npmjs.com/package/@daohaus/local-abis) after this pr goes in - https://github.com/HausDAO/daohaus-monorepo/pull/580

we can probably remove these packages.

# additional items

- [x] we also need to connect npm to our org (it will help people trust the package registry, plus basic metadata on the profile)
- [x] we should add a profile picture that matches the daohaus logo

![Image](https://user-images.githubusercontent.com/5998100/182289934-4d39ef4e-f277-4610-b7d0-3974764017d0.png)

**Comment by skuhlmann** [comment]
I've deprecated the old packages and tried to update the profile

https://www.npmjs.com/~daohaus-protocol
