### ISSUE TITLE
Refactor moloch-v3-context

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo-deprecated#827]
# Details

Review and re-spec the daocontext now that we've had some cycles working with it.

https://github.com/HausDAO/daohaus-monorepo/blob/develop/libs/dao-context/src/DaoContext.tsx

Step one is to set up a meeting to walk though code and places it's used.

### Current implementation notes

- Large context that loads all entities needed for core ui
- Includes filtering/sorting/pagination features for list entities
- Includes entities scoped to the connected address
  - address membership data
  - address proposal vote data

### Limitations/improvement ideas

- Some apps might not want all this data - just a proposal list for instance
  - can we let the dev pick the entities they want loaded
  - maybe the fetch doesn't happen on context load, but on page load - initiated with a hook
  - look into useQuery package
  - could also use prop
     - array of things to load

- Can we try for a useDataList( {entity: 'proposals' })
-- has filterList, sortList, loadMoreEntities

- Some apps might want data across multiple daos
  - or even daos across multiple networks like in hub

- Our style of 'Load More' pagination is difficult to deal with when we need to refresh data because we are only loading one page at a time and building up the list of proposals - if someone has loaded 100's of daos onto that list we're really just storing the next query - so it might reset the entire list to the default query of 1st 10 items

### Exploration

**9.29**
Doing some exploration in dao-context lib to help inform this:

- [x] break out hooks into more manageable files
- [x] add hooks for list actions in proposals/members section
- [x] can we remove dataFetchHelpers.ts from core-app? 

### Execution

**11.28**

- [x] molochv3data component
- [x] molochv3context
- [x] hooks
- [x] refresh all
- [x] fix proposal list page reloads
- [x] clean up yolo
- [x] loadMember and loadProposal
- [x] remove old code

https://hackmd.io/Qkzvzg-dQKmsU4xJ8Sl2hg

**Comment by jordanlesich** [comment]
## Improvement Ideas

- Changing branding to MolochPackV3
- Is a repo for MolochV3 specific UI (Form elements or proposal cards) 
- Needs hooks to simplify fetching
- Should handle the Single DAO app pattern

**Comment by skuhlmann** [comment]
Step one:

- allow a dev to select which entities they want to use

- ease of use
  - more abstracted hooks

- add proposal list


- needs to include a refactor of useParams to use context

**Comment by skuhlmann** [comment]
**create profile-data package**
- profile get w/ dao fetching

**rework moloch-v3-data**
- no need for query class
- all query functions will need to take a graph api key

**rework queries in admin/summon**

**rework moloch-v3-context**
- can we optimize some of the re-renders?
- could we rework our of of the useeffects and just create functions for pagination/filtering/ordering

moving this stuff out into ticket #389 

all this is complete
