### ISSUE TITLE
Minting New Shares results in Error

### ISSUE THREAD

**Issue by boilerrat** [HausDAO/daohaus-monorepo-deprecated#901]
### Feature

Issue DAO Token Proposal

### App

- [Admin](https://admin.daohaus.fun)

### Expected Behavior

Issue new voting shares in goerli v3 DAO.

### Actual Behavior

All entered fields in form appear to be correct. When clicking submit, the error as seen in screen shot below appears.
Unable to submit proposal.

### Steps to Reproduce

1. Click Proposals
2. Click New Proposal
3. Click Issue DAO Tokens
4. Fill Out All Fields of Form
5. Click Submit
6. Recv Error

https://admin.daohaus.fun/#/molochv3/0x5/0x9310c1b1005f733da41e54699132cde232a6a849/new-proposal?formLego=ISSUE

### Browser

Chrome

### DAO Address: 0x9310c1b1005f733da41e54699132cde232a6a849

Screenshot of error
<img width="748" alt="image" src="https://user-images.githubusercontent.com/34731569/192163306-ffae0ea4-c7b1-47df-bdc7-5d87eda7ad66.png">

## Reproduction:
All required fields filled out, incl "0" in  Non Voting Tokens requested
<img width="464" alt="image" src="https://user-images.githubusercontent.com/34731569/192163556-f91ba83d-3afb-4be8-bf2e-8d65537f54ae.png">

Same result:
<img width="748" alt="image" src="https://user-images.githubusercontent.com/34731569/192163591-523b1497-1182-4690-8728-5477abe4018a.png">

**Comment by santteegt** [comment]
I was unable to reproduce this error

**Comment by earth2travis** [comment]
![Image](https://user-images.githubusercontent.com/522182/193859852-9ce1a88f-852b-4027-be03-10539d8dbd63.png)

https://goerli.etherscan.io/tx/0x8f4055a9a4a3b17990cbe71e76d353a464789686cc24177d9841e49c68149951

![Image](https://user-images.githubusercontent.com/522182/193860381-920b6e91-8675-4845-8603-2c37461606e8.png)

**Comment by earth2travis** [comment]
Cannot replicate
