### ISSUE TITLE
Proposal Layout Enhancements

### ISSUE THREAD

**Issue by 7helles** [HausDAO/daohaus-monorepo-deprecated#903]
### Feature

Proposals

### App

- [Admin](https://admin.daohaus.fun)

### Expected Behavior

Filing an issue to capture layout improvements to proposal cards.

### Actual Behavior

1. The right container on proposal cards is small enough that some elements break even on desktop; for example, the proposal status breaks into two lines, and there isn't room for the status and quorum info on the same line. 
- Suggested solution: reduce the width of the left container by 6rem.
- 9/30/22 - This may not be enough to avoid breaking to two lines for all labels, so I'm adding the suggestion to also reduce the font size across the card (minus the title) to ParSm (14 point).
- Additionally, there's no technical reason not to, quorum percentages could be whole numbers instead of adding decimal points.
- With this adjustment, the Status indicator text on the left of the left container and the Details button might overlap. Truncating long statuses after 30 characters with ellipses might address this. (Note: this may be addressed sufficiently by reducing the font size to ParSm?)

2. On mobile, estimate gas is a tappable icon next to the Execute button.
- The icon could be moved above the Execute button and parXs text added displaying the estimated gas, eg: "Min. gas required: 0.004 XDAI". Suggested padding between text and button would be 12px.

### Screenshots and Context

![FireShot Capture 043 - DAOhaus v3 – Figma - www figma com](https://user-images.githubusercontent.com/97971946/192365316-3fc3ba1e-9517-458b-a81b-88ddb8ebe82f.png)
![FireShot Capture 042 - DAOhaus v3 – Figma - www figma com](https://user-images.githubusercontent.com/97971946/192365348-7b827316-09f5-44d1-a6f2-612d356d53fc.png)

**Comment by 7helles** [comment]
e2t pointed out some additional statuses I was unaware of, shown in https://github.com/HausDAO/daohaus-monorepo/issues/860 -- I think "Voting ends in 43 seconds" will still break to two lines, even with an additional 6rem. Adjusting suggestions to include reducing font size to ParSm, as in the following:
![FireShot Capture 059 - DAOhaus Admin - admin daohaus fun](https://user-images.githubusercontent.com/97971946/193346040-80b6e4a9-e96a-4002-af9c-206ceab914ba.png)

**Comment by earth2travis** [comment]
@7helles do you also want to include how we want to handle long titles in this issue

![Image](https://user-images.githubusercontent.com/522182/195916987-4e74b259-77be-4c19-a655-e2e9bdff6bf8.png)

**Comment by earth2travis** [comment]
Jord has already implemented the update to expand the size of the right column

**Comment by earth2travis** [comment]
![Image](https://user-images.githubusercontent.com/522182/195918206-4e3e34a1-dee3-41f3-bd85-6aa8a7f5a671.png)

**Comment by skuhlmann** [comment]
![Image](https://user-images.githubusercontent.com/6923345/200950136-d1b0754c-b39b-4ba2-81ec-baa55fc8413a.png)
![Image](https://user-images.githubusercontent.com/6923345/200950137-da7711c6-36ab-4b11-b7bc-9ec13c2551d1.png)

had to keep the value in the tooltip here because it can be a long number
