### ISSUE TITLE
Propagate Button v2 and Create Ghost Button Component

### ISSUE THREAD

**Issue by 0xRowdy** [HausDAO/daohaus-monorepo-deprecated#932]
Create ghost button 

https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library?node-id=1%3A5

**Comment by earth2travis** [comment]
This PR is ready for review if someone wants to take a look: https://github.com/HausDAO/daohaus-monorepo/pull/1030 @skuhlmann @jordanlesich @santteegt

**Comment by earth2travis** [comment]
@0xRowdy I reopened this issue. We may have missed some ghost buttons that were implemented in https://github.com/HausDAO/daohaus-monorepo/issues/725

## Proposal Cards

<img width="702" alt="image" src="https://user-images.githubusercontent.com/522182/199332117-11359cc5-d9ac-4bf9-b011-6a38bb797284.png">

<img width="702" alt="image" src="https://user-images.githubusercontent.com/522182/199332171-72cef2c7-f706-4623-9868-c93cba49a212.png">

## Proposal Details

<img width="702" alt="image" src="https://user-images.githubusercontent.com/522182/199332429-c234db2e-34a2-4388-b91e-4682b1040c2f.png">

<img width="702" alt="image" src="https://user-images.githubusercontent.com/522182/199332321-b3399b5e-3f1e-4471-8e8f-9a229309e7cb.png">

## Proposal Votes

<img width="501" alt="image" src="https://user-images.githubusercontent.com/522182/199332840-8847af7f-f7ff-44b3-b0b9-34dfac324d89.png">

<img width="604" alt="image" src="https://user-images.githubusercontent.com/522182/199332625-8e7923b3-d870-4817-b99c-8151d49f2460.png">

## Proposal Status

<img width="487" alt="image" src="https://user-images.githubusercontent.com/522182/199333099-b3b1dca6-c95f-44a5-93a1-7f0b792acd5c.png">

<img width="467" alt="image" src="https://user-images.githubusercontent.com/522182/199333013-500ced4b-3714-473a-b807-ef364aa9fdec.png">

## Members

<img width="411" alt="image" src="https://user-images.githubusercontent.com/522182/199333358-b1db4e4f-ef7e-4048-b3da-fbdb8f03f76b.png">

<img width="511" alt="image" src="https://user-images.githubusercontent.com/522182/199333295-049586bd-59e3-49c7-adf7-c15d6e6f3955.png">

## Profile

<img width="663" alt="image" src="https://user-images.githubusercontent.com/522182/199333654-b0a4b73f-de1e-4b51-8daa-fa281a8ab5c1.png">

<img width="663" alt="image" src="https://user-images.githubusercontent.com/522182/199333587-6cd87ecb-664e-4a26-9a22-65e73ac8ef40.png">

**Comment by santteegt** [comment]
### Member Profile with `delegated to` property
<img width="604" alt="image" src="https://user-images.githubusercontent.com/926341/200409914-99016157-7a01-42bc-92e0-e05c56e8674b.png">

**Comment by 0xRowdy** [comment]
I think I got everything except the IconButton. We just redeployed SubGraph and lost some of our existing test data.
