### ISSUE TITLE
remove `react-router` from @daohaus/ui

### ISSUE THREAD

**Issue by brossetti1** [HausDAO/daohaus-monorepo-deprecated#971]
# Problem

- react-router-dom is included in the @daohaus/ui library in one place:
https://github.com/HausDAO/daohaus-monorepo/blob/ef95ebedaa0e23623a430fc4bc3279b854941a4d/libs/ui/src/components/atoms/Link/Link.styles.ts#L0-L1

removing dependencies like this will shrink our packages and make them easier to run externally

# Solution

remove `Link` and manipulate UI link instead -- react-router-link can be manipulated in app level logic

**Comment by 0xRowdy** [comment]
Currently tracking in [#150](https://github.com/HausDAO/monorepo/issues/150). Closing this issue to remove duplication.
