### ISSUE TITLE
Fix Shrinking Button When Spinner is Active

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo-deprecated#989]
### Feature

Button Component

### App

- [Admin](https://admin.daohaus.fun)

### Expected Behavior

Would expect the button to stay the same size

### Actual Behavior

Button is shrinking while spinner is active

### Browser

Brave

### Screenshots and Context

<img width="362" alt="image" src="https://user-images.githubusercontent.com/522182/195926438-e5d98745-6fea-49e3-8ddb-a57161cfc23b.png">

**Comment by 0xRowdy** [comment]
We can handle this by making the text transparent and the spinner loading above.
Could be a button enhancement or a new button variant.
