### ISSUE TITLE
Deprecate Unused Infrastructure

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo-deprecated#996]

**Comment by earth2travis** [comment]
Basically done. Need to shut down Digital Ocean stuff

**Comment by earth2travis** [comment]
@jonathanprozzi is there anything from Digital Ocean that needs to be migrated to a new vendor?

**Comment by jonathanprozzi** [comment]
> @jonathanprozzi is there anything from Digital Ocean that needs to be migrated to a new vendor?

I'm not actually sure -- I believe it was the infra for the jobs only, but I'll check. @alexkeating maybe we can sync real fast about this when you're able to. Want to be completely sure we don't have anything on there we need to replace

**Comment by jordanlesich** [comment]
@jonathanprozzi @earth2travis There's nothing that we're using in the new mono for this. I'd say it's safe to shut it down.
